### ISSUE TITLE
Not enough memory when running in circleci (no .env available)

### ISSUE THREAD

**Issue by chrismllr** [brysgo/babel-plugin-inline-dotenv#5]
In our CI/CD environment in circleci, we use the environment variables circle provides instead of committing our .env.

When running tests, the console output is flooded with:
```
{ Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Object.config (/home/circleci/javascript/node_modules/dotenv/lib/main.js:30:37)
    at PluginPass.MemberExpression (/home/circleci/javascript/node_modules/babel-plugin-inline-dotenv/index.js:14:40)
    at newFn (/home/circleci/javascript/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/circleci/javascript/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/circleci/javascript/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/circleci/javascript/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/circleci/javascript/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/circleci/javascript/node_modules/babel-traverse/lib/context.js:108:19) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
```

As the .env is not present. This leads to a `not enough memory` error which fails our test suite.
```
ENOMEM: not enough memory, read
      
      at Object.fs.readSync (fs.js:682:18)
      at tryReadSync (fs.js:543:20)
      at Object.fs.readFileSync (fs.js:578:19)
      at Object.<anonymous>
```

Is there a way disable in some way for a CI env? Maybe this is scripting we have to do on our end.

**Comment by brysgo** [comment]
hey @chrismllr (I think we met at react conf), not sure if this helps, but options passed in the babel config go straight through to the [dotenv](https://github.com/motdotla/dotenv) package.

**Comment by chrismllr** [comment]
Haha, hey @brysgo! What a coincidence 😆 

So for the time being i've used babel's `env` to disable `inline-dotenv` in test environment - Will probably have to get more crafty once running prod builds through CI as well, but you've got me on the right track. Thanks!

**Comment by brysgo** [comment]
Glad you found a solution! I'm closing this for now, but you should reopen it when you find / start looking for a better solution.
